Nombre: STALIN JITALA
MATERIA: METODOS NUMERICOS
Profesor: Ingeniero Jonathan Zea

Ejercicio 1

Multiplicaciones matriz-matriz.

In [ ]:
import numpy as np

# Ejercicio 1a
A1a = np.array([[2, -3], [3, -1], [5, 2]])
B1a = np.array([[1, 5], [2, 0]])
C1a = np.dot(A1a, B1a)
print("Resultado 1a:")
print(C1a)

# Ejercicio 1b
A1b = np.array([[2, -3, 1], [3, -1, 0]])
B1b = np.array([[1, -1, -4], [3, -1, 2], [2, 0, 0]])
C1b = np.dot(A1b, B1b)
print("Resultado 1b:")
print(C1b)

# Ejercicio 1c
A1c = np.array([[1, 2, 1, 0], [2, 0, -1, -2], [0, 1, 0, -3]])
B1c = np.array([[1, 2], [2, 0], [-1, 3], [1, 1]])
C1c = np.dot(A1c, B1c)
print("Resultado 1c:")
print(C1c)

# Ejercicio 1d
A1d = np.array([[3, 1, 2], [5, 2, 4], [1, 1, 3], [-2, 0, -4]])
B1d = np.array([[0, 1], [1, 2], [-2, -3]])
C1d = np.dot(A1d, B1d)
print("Resultado 1d:")
print(C1d)


Resultado 1a:
[[-4 10]
 [ 1 15]
 [ 9 25]]
Resultado 1b:
[[ -5   1 -14]
 [  0  -2 -14]]
Resultado 1c:
[[ 4  5]
 [ 1 -1]
 [-1 -3]]
Resultado 1d:
[[-3 -1]
 [-6 -3]
 [-5 -6]
 [ 8 10]]


Ejercicio 2

Determinar cuáles matrices son no singulares y calcular su inversa.

In [ ]:
# Función para verificar si una matriz es singular
def es_singular(A):
    return np.linalg.det(A) == 0

# Ejercicio a
A2a = np.array([[4, 3, 6], [2, -3, -2], [1, 0, 1]])
print("Determinante 2a:", np.linalg.det(A2a))
if not es_singular(A2a):
    inv_A2a = np.linalg.inv(A2a)
    print("Inversa 2a:")
    print(inv_A2a)

# Ejercicio b
A2b = np.array([[1, 2, 0], [0, 1, 1], [2, -1, 1]])
print("Determinante 2b:", np.linalg.det(A2b))
if not es_singular(A2b):
    inv_A2b = np.linalg.inv(A2b)
    print("Inversa 2b:")
    print(inv_A2b)

# Ejercicio c
A2c = np.array([[2, 3, 1], [4, 5, 2], [3, 4, 1]])
print("Determinante 2c:", np.linalg.det(A2c))
if not es_singular(A2c):
    inv_A2c = np.linalg.inv(A2c)
    print("Inversa 2c:")
    print(inv_A2c)

# Ejercicio d
A2d = np.array([[1, 1, 0, 1], [2, 3, 4, 0], [0, -1, 1, 1], [1, 3, -2, 1]])
print("Determinante 2d:", np.linalg.det(A2d))
if not es_singular(A2d):
    inv_A2d = np.linalg.inv(A2d)
    print("Inversa 2d:")
    print(inv_A2d)


Determinante 2a: -5.999999999999997
Inversa 2a:
[[ 0.5         0.5        -2.        ]
 [ 0.66666667  0.33333333 -3.33333333]
 [-0.5        -0.5         3.        ]]
Determinante 2b: 6.000000000000001
Inversa 2b:
[[ 0.33333333 -0.33333333  0.33333333]
 [ 0.33333333  0.16666667 -0.16666667]
 [-0.33333333  0.83333333  0.16666667]]
Determinante 2c: 1.0
Inversa 2c:
[[-3.  1.  1.]
 [ 2. -1.  0.]
 [ 1.  1. -2.]]
Determinante 2d: 9.999999999999998
Inversa 2d:
[[ 2.5 -0.2 -1.4 -1.1]
 [-1.   0.2  0.4  0.6]
 [-0.5  0.2  0.4  0.1]
 [-0.5  0.   1.   0.5]]


Ejercicio 3

Resolver los sistemas lineales 4x4.

In [ ]:
# Ejercicio a
A3 = np.array([[1, -2, 2, 3], [1, 3, -1, 2], [2, 1, 3, -4], [2, 3, -4, 2]])
b3a = np.array([6, 1, -2, 5])
x3a = np.linalg.solve(A3, b3a)
print("Solución 3a:")
print(x3a)

# Ejercicio b
b3b = np.array([1, 4, 2, 4])
x3b = np.linalg.solve(A3, b3b)
print("Solución 3b:")
print(x3b)


Solución 3a:
[ 2.21827411 -1.18274112 -0.59390863  0.8680203 ]
Solución 3b:
[0.91370558 0.86294416 0.30456853 0.40101523]


Ejercicio 4

Encontrar los valores de α que hacen que la matriz sea singular.

In [ ]:
# Función para encontrar los valores de alpha que hacen singular a la matriz
def encontrar_alpha_singular():
    alphas = np.linspace(-10, 10, 1000)
    for alpha in alphas:
        A4 = np.array([[1, -1, 1], [2, 0, 1], [0, alpha, alpha/2]])
        if np.linalg.det(A4) == 0:
            print(f"Valor de alpha que hace la matriz singular: {alpha}")

encontrar_alpha_singular()


Ejercicio 5

Resolver los sistemas lineales.

In [ ]:
# Ejercicio a
A5a = np.array([[1, 2, 1], [2, 1, 0], [3, -1, 2]])
b5a = np.array([2, -1, 3])
x5a = np.linalg.solve(A5a, b5a)
print("Solución 5a:")
print(x5a)

# Ejercicio b
A5b = np.array([[2, -1, 1], [1, 3, 2], [1, -1, 2]])
b5b = np.array([3, -1, 4])
x5b = np.linalg.solve(A5b, b5b)
print("Solución 5b:")
print(x5b)


Solución 5a:
[-0.54545455  0.09090909  2.36363636]
Solución 5b:
[ 0.25 -1.25  1.25]


Ejercicio 6

Factorizar las matrices en la descomposición LU.

In [ ]:
from scipy.linalg import lu

# Ejercicio a
A6a = np.array([[2, 1, 1], [1, 2, 2], [1, 2, 3]])
P, L, U = lu(A6a)
print("Descomposición LU 6a:")
print("L:")
print(L)
print("U:")
print(U)

# Ejercicio b
A6b = np.array([[1, 1, 2, 1], [3, 4, -1, 2], [5, 1, -1, -3], [2, 2, 3, 2]])
P, L, U = lu(A6b)
print("Descomposición LU 6b:")
print("L:")
print(L)
print("U:")
print(U)


Descomposición LU 6a:
L:
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 1.  1. ]]
U:
[[2.  1.  1. ]
 [0.  1.5 1.5]
 [0.  0.  1. ]]
Descomposición LU 6b:
L:
[[1.         0.         0.         0.        ]
 [0.6        1.         0.         0.        ]
 [0.4        0.47058824 1.         0.        ]
 [0.2        0.23529412 0.63934426 1.        ]]
U:
[[ 5.          1.         -1.         -3.        ]
 [ 0.          3.4        -0.4         3.8       ]
 [ 0.          0.          3.58823529  1.41176471]
 [ 0.          0.          0.         -0.19672131]]


Ejercicio 7

In [3]:
import numpy as np

def descomposicion_lu(A):
    """Realiza la descomposición LU utilizando el método de Doolittle."""
    n = A.shape[0]
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        L[i, i] = 1
        for j in range(i, n):
            U[i, j] = A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))
        for j in range(i + 1, n):
            L[j, i] = (A[j, i] - sum(L[j, k] * U[k, i] for k in range(i))) / U[i, i]

    return L, U

def sustitucion_adelante(L, b):
    """Resuelve el sistema Ly = b para y."""
    n = L.shape[0]
    y = np.zeros(n)
    for i in range(n):
        y[i] = b[i] - sum(L[i, j] * y[j] for j in range(i))
    return y

def sustitucion_atras(U, y):
    """Resuelve el sistema Ux = y para x."""
    n = U.shape[0]
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - sum(U[i, j] * x[j] for j in range(i + 1, n))) / U[i, i]
    return x

def resolver_sistema_lu(A, b):
    """Resuelve el sistema Ax = b usando la descomposición LU."""
    L, U = descomposicion_lu(A)
    y = sustitucion_adelante(L, b)
    x = sustitucion_atras(U, y)
    return x


# Sistema a
A_a = np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]], dtype=float)
b_a = np.array([-1, 0, 4], dtype=float)

# Sistema b
A_b = np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]], dtype=float)
b_b = np.array([1.984, -5.049, -3.895], dtype=float)

# Sistema c
A_c = np.array([[1, 0, 0, 0], [1, 1.5, 0, 0], [0, -3, 0.5, 0], [0, 2, 1, 1]], dtype=float)
b_c = np.array([3, 4.5, -6.6, 0.8], dtype=float)

# Sistema d
A_d = np.array([[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6, 0, 1.1973], [-1, -5.2107, 1.1111, 0], [6.0235, 7, 0, -4.1561]], dtype=float)
b_d = np.array([17.102, -6.1593, 3.0004, 0], dtype=float)

# Solución de los sistemas
x_a = resolver_sistema_lu(A_a, b_a)
x_b = resolver_sistema_lu(A_b, b_b)
x_c = resolver_sistema_lu(A_c, b_c)
x_d = resolver_sistema_lu(A_d, b_d)

print("Solución para el sistema a:", x_a)
print("Solución para el sistema b:", x_b)
print("Solución para el sistema c:", x_c)
print("Solución para el sistema d:", x_d)


Solución para el sistema a: [ 1.  2. -1.]
Solución para el sistema b: [1. 1. 1.]
Solución para el sistema c: [ 3.   1.  -7.2  6. ]
Solución para el sistema d: [2.9398512  0.0706777  5.67773512 4.37981223]
